version: "3.9"
services:
  frontend:
    image: mweiershaeuser/beiboot-frontend
    restart: always
    ports:
      - "8060:80"

  backend:
    image: mweiershaeuser/beiboot-backend
    restart: always
    ports:
      - "8061:1337"
    volumes:
      - type: bind
        source: ./db
        target: /beiboot-backend/.tmp
      - type: bind
        source: ./assets
        target: /beiboot-backend/public
